apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: your_username
        - name: POSTGRES_PASSWORD
          value: your_password
        - name: POSTGRES_DB
          value: your_database_name
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-scripts
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS example (
      id serial PRIMARY KEY,
      name varchar(255)
    );

