apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: aniruddhadockerid/backend:2.0
        ports:
        - containerPort: 8081
        env:
        - name: PG_HOST
          value: postgres
        - name: PG_PORT
          value: "5432"
        - name: PG_USER
          value: psql
        - name: PG_PASSWORD
          value: LevelUp
        - name: PG_DBNAME
          value: tasks
        readinessProbe:
            httpGet:
              path: /items
              port: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
